### ISSUE TITLE
ControlMySpa service doesn't run anymore

### ISSUE THREAD

**Issue by MartinGoX** [mikakoivisto/controlmyspa-ha-mqtt#10]
Hi Mika.
Sorry to disturb... do you know about problems to run the controlmyspa-ha-mqtt service on a HA version
Home Assistant 2023.7.1 Supervisor 2023.07.1 Operating System 10.3
Since today or yesterday the service stops after few seconds and the protocoll log shows a couple of lines of json code; here are a few of the very end:
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
Node.js v18.16.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

I noticed that the ControlMySpa app was updated by Balboa on July 4th but didn't know if the did something critical...?

Thanks in advance and best regards
Martin

**Comment by MartinGoX** [comment]
Hi again,
I just tried with an older backup (sure that it was working at the time the backup was made) but it doesn't work either.
My assumption is that Balboa did some change(s) in the interface or so...
Best regards
Martin

**Comment by mikakoivisto** [comment]
Looks like controlmyspa server certificate was renewed and not setup correctly again. I think this same exact issue happened last year too.

**Comment by MartinGoX** [comment]
Ah, ok.

Is that something you can change/correct or has Balboa to do it?

10.07.2023 14:15:29 Mika Koivisto ***@***.***>:

**Comment by mikakoivisto** [comment]
You can set environment variable NODE_TLS_REJECT_UNAUTHORIZED = 0 to bypass the TLS validation that NodeJS http client does. Another possible fix is to manually add the intermedia certificate that is currently missing from their TLS handshake to your systems trusted CA roots but the first option is much easier.

**Comment by MartinGoX** [comment]
Ok, thanks, I will give it a try...

10.07.2023 14:26:46 Mika Koivisto ***@***.***>:

**Comment by MartinGoX** [comment]
Hi

Honestly speaking, I do not find a place where to set the environment 
variable to zero. I know about developing software but not on Linux 
systems...
I also didn't know where the controlmyspa-ha-mqtt files are located on 
the HA system.

It would be a great help if you could give me some more details.

Thanks a lot and best regards
Martin


------ Originalnachricht ------
Von "Mika Koivisto" ***@***.***>
An "mikakoivisto/controlmyspa-ha-mqtt" 
***@***.***>
Cc "MartinGoX" ***@***.***>; "Author" 
***@***.***>
Datum 10.07.2023 14:26:45
Betreff Re: [mikakoivisto/controlmyspa-ha-mqtt] ControlMySpa service 
doesn't run anymore (Issue #10)

**Comment by MartinGoX** [comment]
Good morning.

Having further asked Google regarding NODE_TLS_REJECT_UNAUTHORIZED=0 I'm 
a bit anxious if that solution works for me as I'm accessing HA via 
duckdns.org by HTTPS only...?

Best regards
Martin


------ Originalnachricht ------
Von "Martin Gottschlich" ***@***.***>
An "mikakoivisto/controlmyspa-ha-mqtt" 
***@***.***>
Datum 10.07.2023 20:10:51
Betreff Re[2]: [mikakoivisto/controlmyspa-ha-mqtt] ControlMySpa service 
doesn't run anymore (Issue #10)

**Comment by mikakoivisto** [comment]
It's set in the same place where you set your controlmyspa username and password and mqtt settings so either in the docker-compose.yml or docker.env depending on how your setup is. It only affects the controlmyspa docker image and nothing else.

**Comment by MartinGoX** [comment]
Thanks for your fast reply.
I did the configuration in the UI, so didn't saw a place to add that. I will switch to yaml and edit there.

Have a nice day
Martin

11.07.2023 07:49:50 Mika Koivisto ***@***.***>:

**Comment by mikakoivisto** [comment]
I added it also as option for the homeassistant addon so it might be available in the UI also now.

**Comment by dlysnes** [comment]
FYI I contacted Balboa again (same as last year). Certificate chain is complete serverside now.

**Comment by MartinGoX** [comment]
Ok, thank you for the info...but what does that mean for me/you/the addon?

**Comment by mikakoivisto** [comment]
Not showing complete certificate chain for me but in my latest commit I added full CA chain to NodeJS trusted certificates so it should no longer complain about it and should work without the NODE_TLS_REJECT_UNAUTHORIZED hack.

**Comment by garysargentpersonal** [comment]
I'm getting a 504 gateway timeout for https://iot.controlmyspa.com/idm/tokenEndpoint

Is this working for anyone?

**Comment by garysargentpersonal** [comment]
And almost as soon as I posted that it started working again! Their servers really are useless!
