### ISSUE TITLE
Docker application on my Synology NAS

### ISSUE THREAD

**Issue by nuiler** [mikakoivisto/controlmyspa-ha-mqtt#13]
I would like to run controlmyspa-ha-mqtt as a Docker application on my Synology NAS. 
Unfortunately, it terminates unexpectedly after starting.

Do I have to create a config in advance.
Can I point this to a folder

**Comment by mikakoivisto** [comment]
You configure it through environment variables. See README.md

**Comment by nuiler** [comment]
mikakoivisto-controlmyspa-ha-mqtt-1
date,stream,content
2024/03/18 11:27:18,stdout,Node.js v18.16.1

2024/03/18 11:27:18,stdout,

2024/03/18 11:27:18,stdout,[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m

2024/03/18 11:27:18,stdout,    at [90m/usr/src/app/[39mlib/spa.js:24:12

2024/03/18 11:27:18,stdout,[90m    at Spa.emit (node:events:525:35)[39m

2024/03/18 11:27:18,stdout,    at Spa.<anonymous> [90m(/usr/src/app/[39mlib/spa.js:34:33[90m)[39m

2024/03/18 11:27:18,stdout,TypeError: Cannot read properties of null (reading 'expires_in')

2024/03/18 11:27:18,stdout,

2024/03/18 11:27:18,stdout,                                ^

2024/03/18 11:27:18,stdout,"      }, (self.client.tokenData.expires_in - 60) * 1000);
"
2024/03/18 11:27:18,stdout,/usr/src/app/lib/spa.js:34

2024/03/18 11:27:16,stdout,failed to login

2024/03/18 11:27:14,stdout,  [34;1mapp:info [0mMQTT connection established [34m+0ms[0m

2024/03/18 11:22:21,stdout,Node.js v18.16.1

2024/03/18 11:22:21,stdout,

2024/03/18 11:22:21,stdout,[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m

2024/03/18 11:22:21,stdout,    at [90m/usr/src/app/[39mlib/spa.js:24:12

2024/03/18 11:22:21,stdout,[90m    at Spa.emit (node:events:525:35)[39m

2024/03/18 11:22:21,stdout,    at Spa.<anonymous> [90m(/usr/src/app/[39mlib/spa.js:34:33[90m)[39m

2024/03/18 11:22:21,stdout,TypeError: Cannot read properties of null (reading 'expires_in')

2024/03/18 11:22:21,stdout,

2024/03/18 11:22:21,stdout,                                ^

2024/03/18 11:22:21,stdout,"      }, (self.client.tokenData.expires_in - 60) * 1000);
"
2024/03/18 11:22:21,stdout,/usr/src/app/lib/spa.js:34

2024/03/18 11:22:21,stdout,failed to login

2024/03/18 11:22:20,stdout,  [34;1mapp:info [0mMQTT connection established [34m+0ms[0m
