### ISSUE TITLE
failed to log in

### ISSUE THREAD

**Issue by MaximCernyRecognize** [mikakoivisto/controlmyspa-ha-mqtt#14]
Since approximately 2 weeks the integration stopped working:

```
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1
  app:debug {"mqttHost":"192.168.68.151","mqttPort":"1883","mqttUser":"maxim","mqttPass":"***REMOVED***","hassTopic":"homeassistant/status","spaUser":"cerny@amaxim.cz","spaPassword":"***REMOVED***","useCelsius":true,"refreshSpa":1} +0ms
(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
failed to login
/usr/src/app/lib/spa.js:34
      }, (self.client.tokenData.expires_in - 60) * 1000);
                                ^

TypeError: Cannot read properties of null (reading 'expires_in')
    at Spa.<anonymous> (/usr/src/app/lib/spa.js:34:33)
    at Spa.emit (node:events:525:35)
    at /usr/src/app/lib/spa.js:24:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1
``` 

I am able to log in with username/password combination to https://idmqa.controlmyspa.com/oxauth/login - I didn't change anything.

**Comment by mikakoivisto** [comment]
Looks like their incompetent IT admin has messed up the TLS certificate chain again. You can set this environment variable to make nodejs ignore it: NODE_TLS_REJECT_UNAUTHORIZED=0

**Comment by MaximCernyRecognize** [comment]
I already set this parameter but unfortunately that did not help.

**Comment by mikakoivisto** [comment]
Have you logged in to the ControlMySpa app and accepted their new terms of service? On 18. Mar 2024, at 17.36, MaximCernyRecognize ***@***.***> wrote:﻿
I already set this parameter but unfortunately that did not help.

**Comment by MaximCernyRecognize** [comment]
I tried to log out and log in in the app (ios) but I don't see anything about terms of service (maybe I accepted that some time ago).

**Comment by hgop67** [comment]
I see the same problem. The CMS phone app works and the https://iot.controlmyspa.com/ page works but the HA integration stopped working with the exact same error message as reported above.  
Tried the TLS setting but did not work.

**Comment by mikakoivisto** [comment]
It seems they've changed the API just slightly. For some reason my running system was not affected but I was able to reproduce the issue. I'll eventually have to rewrite the whole library I was depending on but now did a quick fix by forking it and fixing the login which it was incorrectly detecting as failing. https://github.com/mikakoivisto/controlmyspa-ha-mqtt/commit/ea2ff5c74c13dbc6e6e66eb86fd33e417dd75d0e

The latest build should now work.
