### ISSUE TITLE
Maximum temperature limited to 37 degrees C

### ISSUE THREAD

**Issue by bristolbaz** [mikakoivisto/controlmyspa-ha-mqtt#16]
Thank you so much for this integration, it's fantastic.

I am unable to set the heat temperature above 37 C  in HA - any ideas?  I can set to a maximum of 40 C via the app and the panel.

**Comment by bristolbaz** [comment]
Apologies, it seems to be an issue in HA rather than this

**Comment by mikakoivisto** [comment]
I think the max temp is dependent on the temperature range high or low. High allows 40 where as for low I think the max is 37 at least in my Novitek spa. The mqtt autodiscovery sets it based on the mode and what your spa reports the range to be.
