### ISSUE TITLE
Hardware Question 

### ISSUE THREAD

**Issue by lempparisi** [mikakoivisto/controlmyspa-ha-mqtt#20]
Hi,

So if I understand correctly this integration needs this product?
https://novitek.fi/tuote/control-my-spa-etaohjausjarjestelma/

And then I can control my hot tub remotely with home assistant?

**Comment by mikakoivisto** [comment]
Yeah, if your spa didn't come with the module then that is the one. This solution is based on reverse engineered API used by the official ControlMySpa APP. The library I based this integration is no longer maintained by the original author but I try to keep it working as I want to control my spa from home assistant.
