### ISSUE TITLE
temp.step change to 1?

### ISSUE THREAD

**Issue by JSkier21** [mikakoivisto/controlmyspa-ha-mqtt#3]
Greetings,

Throwing this out there for discussion before a PR, I noticed that with temp being 0.5, HA struggles sometimes submitting a new temperature if at .5 decimal (NaN error). Side note, it seems MQTT is reporting the temp without decimal. 

Not sure how this tub works in Celsius land, although I could test that out in a few weeks. Would removing the decimal create any headaches or drawbacks, settings temp.step to 1?

Picture of climate card:
![image](https://user-images.githubusercontent.com/3190223/148094798-07a873ed-cf11-49bb-8579-b3033fd60eec.png)

**Comment by JSkier21** [comment]
Did some more playing around with this, I think this is more of a problem with the rate limiting on this thing 😥 Closing this.

**Comment by mikakoivisto** [comment]
There's some unstability in the current implementation due to lack of error handling. I have improvements coming.
