### ISSUE TITLE
TypeError: Cannot read properties of null (reading '_id')

### ISSUE THREAD

**Issue by JSkier21** [mikakoivisto/controlmyspa-ha-mqtt#6]
UPDATE:
I figured it out. I'm using my own MQTT outside of docker, and what happens is a race condition in which the container tries to immediately push data to MQTT and assumes the spa values from the IoT server are available (they're not). The code should wait for a successful cloud connection before trying to parse values. My workaround was to stop mosquitto, start the container and watch the mqtt errors from it, then start mosquitto service again.

I cannot seem to get this to log in with ControlMySpa IoT over HTTPS. Perhaps the login process is not called with the rewrite?

```
spa.js:87
    return this.client.currentSpa._id;
                                  ^
```

**Comment by mikakoivisto** [comment]
Thanks for reporting the issue. I wasn't able to reproduce the issue. It should not try to push any data to from Spa until it is actually ready. Would you mind taking a stab at fixing it and send me a pull request? 

ControlMySpa.js init() function calls login.

**Comment by JSkier21** [comment]
> Thanks for reporting the issue. I wasn't able to reproduce the issue. It should not try to push any data to from Spa until it is actually ready. Would you mind taking a stab at fixing it and send me a pull request?
> 
> ControlMySpa.js init() function calls login.

Sure thing, I will take a look next week 🙂
