### ISSUE TITLE
Can't get it running in HA

### ISSUE THREAD

**Issue by MartinGoX** [mikakoivisto/controlmyspa-ha-mqtt#8]
Hello Mika,
could you please give me some assistance to get your ControlMySpa integration running in HA? I installed it as an AddOn, this works fine. But when starting it the log protocoll says the following:
...s6-rc: info: service legacy-services successfully started
/run/s6/basedir/scripts/rc.init: line 76: run.sh: not found
...
As I'm not familar with Linux systems I have no idea how to proceed.
My HA version is
Home Assistant 2023.5.3, Supervisor 2023.04.1, Operating System 10.1
running on an Intel NUC.
Additionally the Mosquitto MQTT broker is installed and (as it seems) correctly configured and it's running.

I would really appriciate if you have any hints or advices to get it running.
Thanks in advance and best regards
Martin

**Comment by mikakoivisto** [comment]
I use the docker version of HA and this AddOn was contributed to me so I don't have anyway of testing it. The run.sh is included in the image build but based on the error it looks like it's looking for it from some other directory than where it is. I added an absolute path to it. Try if that works.

**Comment by MartinGoX** [comment]
oh, wow, thank you for your fast reply. With this change the above mentioned error disappear but the log says now:
2023-05-22T12:06:42.120Z app:info Spa initialized
2023-05-22T12:06:42.131Z app:info Starting mqtt discovery
2023-05-22T12:06:42.149Z app:info Ending mqtt discovery
2023-05-22T12:06:42.731Z app:error Unable to connect to MQTT broker. getaddrinfo ENOTFOUND mqtt
Do you have any further helping hint?

**Comment by mikakoivisto** [comment]
It's looking for MQTT broker from hostname mqtt. You need to configure the actual one. Sadly I don't know where or how that is done with supervisor.

**Comment by MartinGoX** [comment]
oh, wow, thank you for your fast reply. With this change the above mentioned error disappear but the log says now:
2023-05-22T12:06:42.120Z app:info Spa initialized
2023-05-22T12:06:42.131Z app:info Starting mqtt discovery
2023-05-22T12:06:42.149Z app:info Ending mqtt discovery
2023-05-22T12:06:42.731Z app:error Unable to connect to MQTT broker. getaddrinfo ENOTFOUND mqtt
Do you have any further helping hint?

**Comment by MartinGoX** [comment]
YEAH, it works!
It was the wrong MQTT hostname, as you thought.
One last small question: the parameter "refreh_spa" is used to be in seconds? Is the default of 5 good and not too fast?

Thank you again for your great help and best regards
Martin
