### ISSUE TITLE
HA update 2023.5.4 - current temp missing

### ISSUE THREAD

**Issue by dlysnes** [mikakoivisto/controlmyspa-ha-mqtt#9]
Not sure what might be wrong, but after upgrading HA core to 2023.5.4 the current temperature is missing.
Running HA in proxmox and sep vm with docker for controlmysqa-mqtt. Restarted both HA and docker a few times.
Was there any changes in HA that causes this? Any logs I can provide? See screenshot where Current temp is shown unavailable.
![image](https://github.com/mikakoivisto/controlmyspa-ha-mqtt/assets/3194140/e6d1257c-8606-4955-8cbb-1c6b402fde50)

**Comment by dlysnes** [comment]
Forget it. Probably api issua, back now 😊
Thanx for a very good implementation!!

**Comment by mikakoivisto** [comment]
The current temperature is not always available from the API. The spa has to be on Ready and even then at times it's not providing it. All the values are published to MQTT with retain flag so it should show the most recent value but depending how your mqtt is setup those might get reset on restart.
